kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "..fullname" . }}-consul-agent-config 
  namespace: default
data:
  agent.hcl: |
    datacenter = "{{ .Values.consul.datacenter }}"
    data_dir = "/opt/consul/"
  service.hcl: |
    service {
      name = "{{ include "..servicename" . }}"
      port = {{ .Values.service.containerPort }}
      tags = [
        {{- range .Values.additionalServiceTags }}"{{ . }}",
        {{- end -}}
      ]

      connect {
        sidecar_service {
          {{- if not (empty .Values.upstreams) -}}
            proxy {
              upstreams = [{{- range .Values.upstreams }}
              {
                destination_name = "{{ .service }}",
                local_bind_port = {{ .port }},
              },
              {{- end -}}]
            }
          {{- end -}} 
        }
      }
    }
