apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "..fullname" . }}
  labels:
    {{- include "..labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "..selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "..selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "..servicename" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        # Login to consul using kubernetes auth
        - name: consul-login
          image: consul:1.7.2
          env:
            - name: CONSUL_HTTP_ADDR
              value: {{ .Values.consul.host }}:8500
          volumeMounts:
            - name: consul-token
              mountPath: /var/run/secrets/consul/
          command: 
            - consul
            - login
            - -method
            - {{ .Values.consul.authMethod }} 
            - -token-sink-file
            - /var/run/secrets/consul/consul.token
            - -bearer-token-file
            - /var/run/secrets/kubernetes.io/serviceaccount/token
      containers:
        # Main container
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.service.check }}
              port: http
          readinessProbe:
            httpGet:
              path: {{ .Values.service.check }}
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        # Sidecars
        - name: consul-agent
          image: {{ .Values.consul.image }} 
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          env:
            - name: CONSUL_HTTP_TOKEN_FILE
              value: /var/run/secrets/consul/consul.token 
          command: [
              "consul", "agent", 
                "-retry-join", "{{ .Values.consul.host }}", 
                "-config-dir", "/etc/consul.d/",
          ]
          lifecycle:
            postStart:
              exec:
                command: 
                  - /bin/sh
                  - /opt/scripts/post-start-agent-token.sh
            preStop:
              exec:
                command: ["consul", "logout"]
          volumeMounts:
            - name: consul-agent-config
              mountPath: /etc/consul.d/
            - name: startup-scripts 
              mountPath: /opt/scripts/
            - name: consul-token
              mountPath: /var/run/secrets/consul/
        - name: sidecar-proxy
          image: {{ .Values.consul.image }} 
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          env:
            - name: CONSUL_HTTP_TOKEN_FILE
              value: /var/run/secrets/consul/consul.token 
          command: ["consul", "connect", "proxy", "-sidecar-for", "{{ include "..servicename" . }}"]
          volumeMounts:
            - name: consul-token
              mountPath: /var/run/secrets/consul/
          ports:
            - name: proxy
              containerPort: 21000
              protocol: TCP
      volumes:
        - name: consul-agent-config
          configMap:
            name: {{ include "..fullname" . }}-consul-agent-config
        - name: startup-scripts
          configMap:
            name: {{ include "..fullname" . }}-startup-scripts
        - name: consul-token
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
