apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "..fullname" . }}
  labels:
    {{- include "..labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "..selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "..selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "..serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        # Main container
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.service.check }}
              port: http
          readinessProbe:
            httpGet:
              path: {{ .Values.service.check }}
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        # Sidecars
        - name: consul-agent
          image: {{ .Values.consul.image }} 
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          command: ["consul", "agent", "-retry-join", "{{ .Values.consul.host }}", "-config-dir", "/etc/consul.d/"]
          volumeMounts:
            - name: consul-agent-config
              mountPath: /etc/consul.d/
        - name: sidecar-proxy
          image: {{ .Values.consul.image }} 
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          command: ["consul", "connect", "proxy", "-sidecar-for", "{{ include "..servicename" . }}"]
          ports:
            - name: proxy
              containerPort: 21000
              protocol: TCP
      # Volumes
      volumes:
        - name: consul-agent-config
          configMap:
            name: {{ include "..fullname" . }}-consul-agent-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
